name: Cypress E2E Tests with Mochawesome Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci  # ✅ This installs Cypress and Mochawesome

      - name: Run Cypress Tests with Mochawesome Reporter
        run: npx cypress run

      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports